### ISSUE TITLE
problem running xrun.py after installation

### ISSUE THREAD

**Issue by johnZYW** [VahanaOpenSource/vtol_sizing#1]
Hi Vahana Developers @zlovering @nenanth,

I just built Vahana in Ubnutu and currently faced an error when trying to run **python3 xrun.py** inside the cases/Beta folders. The error message is attached below and i hope you guys can help me with it. Thank you.

Regards,
Yuwen

Invalid MIT-MAGIC-COOKIE-1 key/home/yuwenzhang/Desktop/USYD/VAHANA/vtol_sizing/cases/Beta/create_fea_config.py:281: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  distloadid = np.array([
wrote config.inp file for airframe structure
xrun.py:57: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  fdefault = yaml.load(f)
xrun.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  fyaml = yaml.load(f)
Traceback (most recent call last):
  File "xrun.py", line 92, in <module>
    x = hydraInterface(all_dict)
TypeError: __init__() missing 1 required positional argument: 'MPI_found'

**Comment by nenanth** [comment]
Looks like you need to install mpi and mpi4py

**Comment by johnZYW** [comment]
Thanks for the reply. I installed mpi and mpi4py but the same error shows up. Could you tell me the version of mpi and mpi4py you were using? I think it might just be an issue of different version.
