### ISSUE TITLE
Set-up tips on running BEMT and FEA high fidelity models

### ISSUE THREAD

**Issue by johnZYW** [VahanaOpenSource/vtol_sizing#3]
Hi Hydra Developer @nenanth,

I have been using your code for a while now and i think its great, so thanks for making it open-source.  

At the moment, i am trying to model the small 20lbs eVTOL vehicle as demonstrated in your paper **A Scalability Study of the Multirotor Biplane Tailsitter Using Conceptual Sizing**.  With the current fidelity, i am getting much higher weight estimate for fuselage and battery, so i think i may need to use FEA and BEMT to get better estimate for the overall weight. 

I see that FEA and BEMT source code is inside the src source folder but they are currently not set-up in the routine. Is it possible that you can share a template or give some hints on how to set them up properly? Thank you.

Yuwen

**Comment by nenanth** [comment]
Hi Yuwen
Unfortunately that functionality is broken. It's not trivial to get it
working with this version of the code.. there's no easy fix

**Comment by johnZYW** [comment]
Hi Hydra Developer @nenanth,

Ohh, its ok, i will see if i can extend the code to include external code if possible. Thanks for the info anyway. 

Yuwen
